/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelreservationsystem.view;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import lk.ijse.gdse43.hotelroomreservationsystem.view.panal.ModifyReservation;
import lk.ijse.gdse43.hotelroomreservationsystem.view.panal.ModifyRooms;
import lk.ijse.gdse43.hotelroomreservationsystem.view.panal.Reservation;
import lk.ijse.gdse43.hotelroomreservationsystem.view.panal.ViewFullPaymentandPrintBill;
import lk.ijse.gdse43.hotelroomreservationsystem.view.panal.ViewReseveDetail;
import lk.ijse.gdse43.hotelroomreservationsystem.view.panal.ViewRoom;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        loadDate();
        loadTime();
    }
    public void loadDate(){
        Date d=new Date();
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        String date=df.format(d);
        lblDate.setText(date);
    }
    public void loadTime(){
        Timer t=new Timer(0,((e) -> {
            Calendar c=Calendar.getInstance();
            SimpleDateFormat df=new SimpleDateFormat("hh.mm.ss");
            String time=df.format(c.getTime());
            lblTime.setText(time);
        }));
        t.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reservationlabel = new javax.swing.JLabel();
        viewroomlabel = new javax.swing.JLabel();
        viewpaymentlabel = new javax.swing.JLabel();
        viewresevedetaillabel = new javax.swing.JLabel();
        modifyreservatinlabel = new javax.swing.JLabel();
        modifyroomlabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainpanal = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));

        reservationlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reservationlabel.setForeground(new java.awt.Color(255, 255, 255));
        reservationlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelroomreservation/resource/Folder_32.png"))); // NOI18N
        reservationlabel.setText("   Reservation");
        reservationlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservationlabelMouseEntered(evt);
            }
        });

        viewroomlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewroomlabel.setForeground(new java.awt.Color(255, 255, 255));
        viewroomlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelroomreservation/resource/Folder_32.png"))); // NOI18N
        viewroomlabel.setText("   View Rooms");
        viewroomlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewroomlabelMouseClicked(evt);
            }
        });

        viewpaymentlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewpaymentlabel.setForeground(new java.awt.Color(255, 255, 255));
        viewpaymentlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelroomreservation/resource/Folder_32.png"))); // NOI18N
        viewpaymentlabel.setText("   View Payment");
        viewpaymentlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewpaymentlabelMouseClicked(evt);
            }
        });

        viewresevedetaillabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewresevedetaillabel.setForeground(new java.awt.Color(255, 255, 255));
        viewresevedetaillabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelroomreservation/resource/Folder_32.png"))); // NOI18N
        viewresevedetaillabel.setText("   View Reserve Detail");
        viewresevedetaillabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewresevedetaillabelMouseClicked(evt);
            }
        });

        modifyreservatinlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modifyreservatinlabel.setForeground(new java.awt.Color(255, 255, 255));
        modifyreservatinlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelroomreservation/resource/Folder_32.png"))); // NOI18N
        modifyreservatinlabel.setText("   Modify Reservation");
        modifyreservatinlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyreservatinlabelMouseClicked(evt);
            }
        });

        modifyroomlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modifyroomlabel.setForeground(new java.awt.Color(255, 255, 255));
        modifyroomlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelroomreservation/resource/Folder_32.png"))); // NOI18N
        modifyroomlabel.setText("   Modify Room");
        modifyroomlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyroomlabelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelroomreservation/resource/Folder_32.png"))); // NOI18N
        jLabel7.setText("   Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reservationlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(viewroomlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(viewpaymentlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addComponent(viewresevedetaillabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(modifyreservatinlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(modifyroomlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(reservationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(viewroomlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(viewpaymentlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(viewresevedetaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(modifyreservatinlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(modifyroomlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelroomreservation/resource/download.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse43/hotelreservationsystem/view/JPanelFormBackground.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        mainpanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 0, 153));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservationlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationlabelMouseClicked
    Reservation c=new Reservation();
        c.setSize(jLabel1.getSize());
        jLabel1.removeAll();
        jLabel1.add(c);
        jLabel1.repaint();
        jLabel1.revalidate();
                
    }//GEN-LAST:event_reservationlabelMouseClicked

    private void reservationlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationlabelMouseEntered
          // TODO add your handling code here:
    }//GEN-LAST:event_reservationlabelMouseEntered

    private void viewroomlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewroomlabelMouseClicked
        ViewRoom v1= new ViewRoom();
        v1.setSize(jLabel1.getSize());
        jLabel1.removeAll();
        jLabel1.add(v1);
        jLabel1.repaint();
        jLabel1.revalidate();
        
        
    }//GEN-LAST:event_viewroomlabelMouseClicked

    private void viewpaymentlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewpaymentlabelMouseClicked
        ViewFullPaymentandPrintBill v1=new ViewFullPaymentandPrintBill();
        v1.setSize(jLabel1.getSize());
        jLabel1.removeAll();
        jLabel1.add(v1);
        jLabel1.repaint();
        jLabel1.revalidate();
        
        
    }//GEN-LAST:event_viewpaymentlabelMouseClicked

    private void viewresevedetaillabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewresevedetaillabelMouseClicked
        ViewReseveDetail v1= new ViewReseveDetail();
        v1.setSize(jLabel1.getSize());
        jLabel1.removeAll();
        jLabel1.add(v1);
        jLabel1.repaint();
        jLabel1.revalidate();
    }//GEN-LAST:event_viewresevedetaillabelMouseClicked

    private void modifyreservatinlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyreservatinlabelMouseClicked
       ModifyReservation m1=new ModifyReservation();
        m1.setSize(jLabel1.getSize());
        jLabel1.removeAll();
        jLabel1.add(m1);
        jLabel1.repaint();
        jLabel1.revalidate();
       
    }//GEN-LAST:event_modifyreservatinlabelMouseClicked

    private void modifyroomlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyroomlabelMouseClicked
        ModifyRooms r=new ModifyRooms();
        r.setSize(jLabel1.getSize());
        jLabel1.removeAll();
        jLabel1.add(r);
        jLabel1.repaint();
        jLabel1.revalidate();
    }//GEN-LAST:event_modifyroomlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel mainpanal;
    private javax.swing.JLabel modifyreservatinlabel;
    private javax.swing.JLabel modifyroomlabel;
    private javax.swing.JLabel reservationlabel;
    private javax.swing.JLabel viewpaymentlabel;
    private javax.swing.JLabel viewresevedetaillabel;
    private javax.swing.JLabel viewroomlabel;
    // End of variables declaration//GEN-END:variables
}
