/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

/**
 *
 * @author user
 */
public class afterroomreservationnewpayment extends javax.swing.JPanel {

    /**
     * Creates new form afterroomreservationnewpayment
     */
    public afterroomreservationnewpayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelpaymentid = new javax.swing.JLabel();
        labelroomid = new javax.swing.JLabel();
        labelreservationid = new javax.swing.JLabel();
        labelprepayment = new javax.swing.JLabel();
        labelnewamount = new javax.swing.JLabel();
        labeldate = new javax.swing.JLabel();
        labeltime = new javax.swing.JLabel();
        textreservationid = new javax.swing.JTextField();
        textpaymentid = new javax.swing.JTextField();
        textprepayment = new javax.swing.JTextField();
        textroomid = new javax.swing.JTextField();
        texttime = new javax.swing.JTextField();
        textnewamount = new javax.swing.JTextField();
        textdate = new javax.swing.JTextField();
        labelreturncash = new javax.swing.JLabel();
        textreturncash = new javax.swing.JTextField();
        labelupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnreload = new javax.swing.JButton();
        labelguestid = new javax.swing.JLabel();
        textguestid = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText(" New Payment");

        labelpaymentid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelpaymentid.setForeground(new java.awt.Color(102, 102, 255));
        labelpaymentid.setText("Payment Id");

        labelroomid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelroomid.setForeground(new java.awt.Color(102, 102, 255));
        labelroomid.setText("Room Id");

        labelreservationid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelreservationid.setForeground(new java.awt.Color(102, 102, 255));
        labelreservationid.setText("Reservatin Id");

        labelprepayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelprepayment.setForeground(new java.awt.Color(102, 102, 255));
        labelprepayment.setText("Pre Payment");

        labelnewamount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelnewamount.setForeground(new java.awt.Color(102, 102, 255));
        labelnewamount.setText("New Amount");

        labeldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeldate.setForeground(new java.awt.Color(102, 102, 255));
        labeldate.setText("Date");

        labeltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeltime.setForeground(new java.awt.Color(102, 102, 255));
        labeltime.setText("Time");

        textreservationid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textreservationidActionPerformed(evt);
            }
        });

        textroomid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textroomidActionPerformed(evt);
            }
        });

        texttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttimeActionPerformed(evt);
            }
        });

        textnewamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnewamountActionPerformed(evt);
            }
        });

        textdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdateActionPerformed(evt);
            }
        });

        labelreturncash.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelreturncash.setForeground(new java.awt.Color(255, 51, 51));
        labelreturncash.setText("Return Cash");

        labelupdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelupdate.setForeground(new java.awt.Color(102, 102, 255));
        labelupdate.setText("UpDate");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Payment Id", "Reservation Id", "Guest Id", "Room Id", "Date", "Time", "Amount", "Advance"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnreload.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreload.setForeground(new java.awt.Color(102, 102, 255));
        btnreload.setText("Reload");

        labelguestid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelguestid.setForeground(new java.awt.Color(102, 102, 255));
        labelguestid.setText("Guest Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelreservationid))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textreservationid, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelguestid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textguestid, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelroomid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(230, 230, 230)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labeldate)
                                            .addComponent(labeltime))
                                        .addGap(136, 136, 136)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(texttime, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textdate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelupdate)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(labelnewamount)
                                                .addComponent(labelprepayment))
                                            .addGap(40, 40, 40)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textprepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(textnewamount, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(50, 50, 50)
                                                    .addComponent(labelreturncash)
                                                    .addGap(20, 20, 20)
                                                    .addComponent(textreturncash, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(btnreload))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(555, 555, 555)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelreservationid)
                            .addComponent(textreservationid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labeldate)
                            .addComponent(textdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeltime)
                            .addComponent(texttime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelguestid)
                            .addComponent(textguestid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelroomid)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelprepayment)
                            .addComponent(textprepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelnewamount)
                                .addComponent(textnewamount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textreturncash, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelreturncash))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(labelupdate)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreload)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdateActionPerformed

    private void textreservationidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textreservationidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textreservationidActionPerformed

    private void texttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttimeActionPerformed

    private void textnewamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnewamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnewamountActionPerformed

    private void textroomidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textroomidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textroomidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeldate;
    private javax.swing.JLabel labelguestid;
    private javax.swing.JLabel labelnewamount;
    private javax.swing.JLabel labelpaymentid;
    private javax.swing.JLabel labelprepayment;
    private javax.swing.JLabel labelreservationid;
    private javax.swing.JLabel labelreturncash;
    private javax.swing.JLabel labelroomid;
    private javax.swing.JLabel labeltime;
    private javax.swing.JButton labelupdate;
    private javax.swing.JTable table;
    private javax.swing.JTextField textdate;
    private javax.swing.JTextField textguestid;
    private javax.swing.JTextField textnewamount;
    private javax.swing.JTextField textpaymentid;
    private javax.swing.JTextField textprepayment;
    private javax.swing.JTextField textreservationid;
    private javax.swing.JTextField textreturncash;
    private javax.swing.JTextField textroomid;
    private javax.swing.JTextField texttime;
    // End of variables declaration//GEN-END:variables
}
