/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse43.hotelreservationsystem.Controller.GuestController;
import lk.ijse.gdse43.hotelreservationsystem.Controller.ResevenewController;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.GuestDTO;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.ReservationDTO;

/**
 *
 * @author user
 */
public class GuestDetail extends javax.swing.JPanel {

    /**
     * Creates new form GuestDetail
     */
    public GuestDetail(/*java.awt.Frame parent, boolean modal*/) {
       /* super(parent, modal);
        //initComponents();
         table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                
                if (table.getSelectedRow() == -1) return;
                
               textguestid .setText(table.getValueAt(table.getSelectedRow(), 0).toString());
                textname.setText(table.getValueAt(table.getSelectedRow(), 1).toString());
                textcountry.setText(table.getValueAt(table.getSelectedRow(), 2).toString());
                textcity.setText(table.getValueAt(table.getSelectedRow(), 3).toString());
                 textidnumber.setText(table.getValueAt(table.getSelectedRow(), 4).toString());
                  textphone.setText(table.getValueAt(table.getSelectedRow(), 5).toString());
                
            }

            
        });*;*/
        
    }

    GuestDetail(String roomId,String checkIn,String checkOut,String price) {
         initComponents();
         roomidtext.setText(roomId);
         checkintext.setText(checkIn);
         checkouttext.setText(checkOut);
         pricetext.setText(""+price);
         
        
    }

   
   

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelreservationid = new javax.swing.JLabel();
        countrylabel = new javax.swing.JLabel();
        citylabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        idnumberlabel = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        textreservationid = new javax.swing.JTextField();
        textcountry = new javax.swing.JTextField();
        textcity = new javax.swing.JTextField();
        textphone = new javax.swing.JTextField();
        textidnumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        namelabel2 = new javax.swing.JLabel();
        roomidlabel = new javax.swing.JLabel();
        roomidtext = new javax.swing.JTextField();
        checkintext = new javax.swing.JTextField();
        checkinlabel = new javax.swing.JLabel();
        checkouttext = new javax.swing.JTextField();
        checkoutlabel = new javax.swing.JLabel();
        pricetext = new javax.swing.JTextField();
        pricelabel = new javax.swing.JLabel();
        guestidlabel1 = new javax.swing.JLabel();
        textguestid1 = new javax.swing.JTextField();
        btnreseveroom1 = new javax.swing.JButton();
        btnreseveroom2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Enter Guest Detail");

        labelreservationid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelreservationid.setForeground(new java.awt.Color(102, 102, 255));
        labelreservationid.setText("Reservation Id");

        countrylabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        countrylabel.setForeground(new java.awt.Color(102, 102, 255));
        countrylabel.setText("Country");

        citylabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        citylabel.setForeground(new java.awt.Color(102, 102, 255));
        citylabel.setText("City");

        phonelabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phonelabel.setForeground(new java.awt.Color(102, 102, 255));
        phonelabel.setText("Phone");

        idnumberlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        idnumberlabel.setForeground(new java.awt.Color(102, 102, 255));
        idnumberlabel.setText("ID Number");

        textcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcountryActionPerformed(evt);
            }
        });

        textphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textphoneActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Guest Id", "Name", "Country", "City", "Id_Number", "Phone_Number"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Reload");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namelabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        namelabel2.setForeground(new java.awt.Color(102, 102, 255));
        namelabel2.setText("Name");

        roomidlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roomidlabel.setForeground(new java.awt.Color(102, 102, 255));
        roomidlabel.setText("Room Id");

        roomidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomidtextActionPerformed(evt);
            }
        });

        checkintext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkintextActionPerformed(evt);
            }
        });

        checkinlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkinlabel.setForeground(new java.awt.Color(102, 102, 255));
        checkinlabel.setText("Check_In");

        checkouttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkouttextActionPerformed(evt);
            }
        });

        checkoutlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkoutlabel.setForeground(new java.awt.Color(102, 102, 255));
        checkoutlabel.setText("Check_Out");

        pricetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetextActionPerformed(evt);
            }
        });

        pricelabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pricelabel.setForeground(new java.awt.Color(102, 102, 255));
        pricelabel.setText("Price");

        guestidlabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        guestidlabel1.setForeground(new java.awt.Color(102, 102, 255));
        guestidlabel1.setText("Guest Id");

        textguestid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textguestid1ActionPerformed(evt);
            }
        });

        btnreseveroom1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreseveroom1.setForeground(new java.awt.Color(102, 102, 255));
        btnreseveroom1.setText("view Payment");
        btnreseveroom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreseveroom1MouseClicked(evt);
            }
        });
        btnreseveroom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreseveroom1ActionPerformed(evt);
            }
        });

        btnreseveroom2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreseveroom2.setForeground(new java.awt.Color(102, 102, 255));
        btnreseveroom2.setText("Reseve Room");
        btnreseveroom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreseveroom2MouseClicked(evt);
            }
        });
        btnreseveroom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreseveroom2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanalLayout = new javax.swing.GroupLayout(mainPanal);
        mainPanal.setLayout(mainPanalLayout);
        mainPanalLayout.setHorizontalGroup(
            mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanalLayout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanalLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanalLayout.createSequentialGroup()
                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanalLayout.createSequentialGroup()
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(mainPanalLayout.createSequentialGroup()
                                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelreservationid)
                                            .addComponent(guestidlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanalLayout.createSequentialGroup()
                                        .addComponent(namelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textreservationid, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textguestid1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanalLayout.createSequentialGroup()
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(citylabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countrylabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idnumberlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textidnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textcity, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textcountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanalLayout.createSequentialGroup()
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(phonelabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roomidlabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(105, 105, 105)
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textphone, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roomidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanalLayout.createSequentialGroup()
                                        .addComponent(btnreseveroom2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnreseveroom1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanalLayout.createSequentialGroup()
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pricelabel)
                                    .addComponent(checkinlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkoutlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pricetext, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkouttext, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkintext, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanalLayout.createSequentialGroup()
                        .addGap(880, 880, 880)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanalLayout.setVerticalGroup(
            mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanalLayout.createSequentialGroup()
                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkinlabel)
                            .addComponent(checkintext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textreservationid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanalLayout.createSequentialGroup()
                        .addComponent(labelreservationid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanalLayout.createSequentialGroup()
                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkoutlabel)
                                .addComponent(textguestid1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(guestidlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkouttext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanalLayout.createSequentialGroup()
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pricelabel)
                                    .addComponent(pricetext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanalLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countrylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(citylabel)
                                    .addComponent(textcity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idnumberlabel)
                                    .addComponent(textidnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(mainPanalLayout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textphone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonelabel))
                        .addGap(30, 30, 30)
                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomidlabel)
                            .addComponent(roomidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1))
                    .addGroup(mainPanalLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(mainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnreseveroom2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnreseveroom1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcountryActionPerformed

    private void textphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textphoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /* try {
            ArrayList<GuestDTO> guest= GuestController.getAllGuest();
            DefaultTableModel dtm=(DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            
            for (GuestDTO guestDTO : guest) {
                Object[] rowData={guestDTO.getGuest_id(),guestDTO.getName(),guestDTO.getCountry(),guestDTO.getCity(),guestDTO.getId_number(),guestDTO.getPhone_number()};
                
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(GuestDetail.class.getName()).log(Level.SEVERE, null, ex);
        }*/
         
        
            
        
        
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void roomidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomidtextActionPerformed

    private void checkintextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkintextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkintextActionPerformed

    private void checkouttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkouttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkouttextActionPerformed

    private void pricetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetextActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  try {
            ArrayList<GuestDTO> guest= GuestController.getAllGuest();
            DefaultTableModel dtm=(DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            
            for (GuestDTO guestDTO : guest) {
                Object[] rowData={guestDTO.getGuest_id(),guestDTO.getName(),guestDTO.getCountry(),guestDTO.getCity(),guestDTO.getId_number(),guestDTO.getPhone_number()};
                
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(GuestDetail.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void textguestid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textguestid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textguestid1ActionPerformed

    private void btnreseveroom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreseveroom1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreseveroom1MouseClicked

    private void btnreseveroom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreseveroom1ActionPerformed
        String reservationId=textreservationid.getText();
        String guest=textguestid1.getText();
        String roomId=roomidtext.getText();
        String date=checkintext.getText();
        
        String checkIn=checkintext.getText();
        String checkOut=checkouttext.getText();
        
        
        Payment p=new Payment(reservationId,guest,roomId,date,checkIn,checkOut);
        p.setSize(this.getSize());
        mainPanal.removeAll();
        mainPanal.add(p);
        mainPanal.repaint();
        mainPanal.revalidate();
    }//GEN-LAST:event_btnreseveroom1ActionPerformed

    private void btnreseveroom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreseveroom2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreseveroom2MouseClicked

    private void btnreseveroom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreseveroom2ActionPerformed
        GuestDTO guestDto=new GuestDTO(textguestid1.getText(),textname.getText(),textcountry.getText(),textcity.getText(),textidnumber.getText(),textphone.getText());
        
        ArrayList<ReservationDTO> d1=new ArrayList<>();
        ReservationDTO r1=new ReservationDTO(textreservationid.getText(),textguestid1.getText(),roomidtext.getText(),checkintext.getText(),checkouttext.getText(),Double.parseDouble(pricetext.getText()));
        System.out.println(textreservationid.getText()+" "+textguestid1.getText()+" "+roomidtext.getText()+" "+checkintext.getText()+" "+checkouttext.getText()+" "+Double.parseDouble(pricetext.getText()));
        d1.add(r1);
      
        boolean addreseve = ResevenewController.addreseve(guestDto, d1);
            if(addreseve){
                JOptionPane.showMessageDialog(this,"Added");
            }else{
        
                 JOptionPane.showMessageDialog(this," Not Added");
        
            }
    }//GEN-LAST:event_btnreseveroom2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreseveroom1;
    private javax.swing.JButton btnreseveroom2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel checkinlabel;
    private javax.swing.JTextField checkintext;
    private javax.swing.JLabel checkoutlabel;
    private javax.swing.JTextField checkouttext;
    private javax.swing.JLabel citylabel;
    private javax.swing.JLabel countrylabel;
    private javax.swing.JLabel guestidlabel1;
    private javax.swing.JLabel idnumberlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelreservationid;
    private javax.swing.JPanel mainPanal;
    private javax.swing.JLabel namelabel2;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JTextField pricetext;
    private javax.swing.JLabel roomidlabel;
    private javax.swing.JTextField roomidtext;
    private javax.swing.JTable table;
    private javax.swing.JTextField textcity;
    private javax.swing.JTextField textcountry;
    private javax.swing.JTextField textguestid1;
    private javax.swing.JTextField textidnumber;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textphone;
    private javax.swing.JTextField textreservationid;
    // End of variables declaration//GEN-END:variables
}
