/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse43.hotelreservationsystem.Controller.GuestController;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.GuestDTO;
import static org.apache.commons.javaflow.Continuation.cancel;

/**
 *
 * @author user
 */
public class ModifyGuestDetail extends javax.swing.JPanel {

    /**
     * Creates new form ModifyGuestDetail
     */
    public ModifyGuestDetail() {
        initComponents();
        close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelmodifyguestdetail = new javax.swing.JLabel();
        labelguestid = new javax.swing.JLabel();
        labelcountry = new javax.swing.JLabel();
        labelcity = new javax.swing.JLabel();
        labelphone = new javax.swing.JLabel();
        labelidnumber = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        textguestid = new javax.swing.JTextField();
        textcountry = new javax.swing.JTextField();
        textcity = new javax.swing.JTextField();
        textphone = new javax.swing.JTextField();
        textidnumber = new javax.swing.JTextField();
        labelname = new javax.swing.JLabel();
        edit_Btn = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnreload = new javax.swing.JButton();
        labelguestid1 = new javax.swing.JLabel();

        labelmodifyguestdetail.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelmodifyguestdetail.setForeground(new java.awt.Color(255, 51, 102));
        labelmodifyguestdetail.setText(" Modify Guest Detail");

        labelguestid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelguestid.setForeground(new java.awt.Color(102, 102, 255));
        labelguestid.setText("Guest Detail");

        labelcountry.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelcountry.setForeground(new java.awt.Color(102, 102, 255));
        labelcountry.setText("Country");

        labelcity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelcity.setForeground(new java.awt.Color(102, 102, 255));
        labelcity.setText("City");

        labelphone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelphone.setForeground(new java.awt.Color(102, 102, 255));
        labelphone.setText("Phone");

        labelidnumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelidnumber.setForeground(new java.awt.Color(102, 102, 255));
        labelidnumber.setText("ID Number");

        textguestid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textguestidActionPerformed(evt);
            }
        });

        textcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcountryActionPerformed(evt);
            }
        });

        textphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textphoneActionPerformed(evt);
            }
        });

        textidnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidnumberActionPerformed(evt);
            }
        });

        labelname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelname.setForeground(new java.awt.Color(102, 102, 255));
        labelname.setText("Name");

        edit_Btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        edit_Btn.setForeground(new java.awt.Color(102, 102, 255));
        edit_Btn.setText("Edit");
        edit_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_BtnActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndelete.setForeground(new java.awt.Color(102, 102, 255));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Guest Id", "Name", "Country", "City", "Id Number", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnreload.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreload.setForeground(new java.awt.Color(102, 102, 255));
        btnreload.setText("Reload");
        btnreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreloadActionPerformed(evt);
            }
        });

        labelguestid1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelguestid1.setForeground(new java.awt.Color(102, 102, 255));
        labelguestid1.setText("Guest Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelguestid1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textguestid, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelidnumber)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textidnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelcity, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textcity, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(textcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelphone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textphone, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(203, 203, 203)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnreload, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(359, 359, 359))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelguestid, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(442, 442, 442))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edit_Btn)
                        .addGap(28, 28, 28)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1036, 1036, 1036))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(labelmodifyguestdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(labelmodifyguestdetail)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelguestid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnreload))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelguestid1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textguestid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelcity)
                            .addComponent(textcity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelidnumber)
                            .addComponent(textidnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textphone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelphone))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_Btn))))
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcountryActionPerformed

    private void textphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textphoneActionPerformed

    private void edit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_BtnActionPerformed
        try {
            String GID = textguestid.getText();
            String Name = textname.getText();
            String Country = textcountry.getText();
            String city=textcity.getText();
            String Tel = textphone.getText();
            String nic=textidnumber.getText();
            
            GuestDTO guest=new GuestDTO(GID,Name,Country,city,Tel,nic);
            boolean result=GuestController.UpdateGuest(guest);
            if(result){
                JOptionPane.showMessageDialog(this, "Update Success");
                close();
            }else{
                
                JOptionPane.showMessageDialog(this, "Update fail");
                close();
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyGuestDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
      
    }//GEN-LAST:event_edit_BtnActionPerformed

    private void textidnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidnumberActionPerformed

    private void textguestidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textguestidActionPerformed
        try {
            String id=textguestid.getText();
            GuestDTO g1=GuestController.searcshGuest(id);
            System.out.println("oooooooo");
            if(g1!=null){
                textname.setText(g1.getName());
                textcountry.setText(g1.getCountry());
                textcity.setText(g1.getCity());
                textidnumber.setText(g1.getId_number());
                textphone.setText(g1.getPhone_number());
            }  else {
                JOptionPane.showMessageDialog(null, "Guest not found...");
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyGuestDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_textguestidActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
            String id=textguestid.getText();
            boolean result=GuestController.delete(id);
            if(result){
                JOptionPane.showMessageDialog(null, "Delete success");
                close();
            }else{
                
                JOptionPane.showMessageDialog(null, "Delete fail");
                close();
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyGuestDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreloadActionPerformed
         try {
            ArrayList<GuestDTO> guest= GuestController.getAllGuest();
            DefaultTableModel dtm=(DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            
            for (GuestDTO guestDTO : guest) {
                Object[] rowData={guestDTO.getGuest_id(),guestDTO.getName(),guestDTO.getCountry(),guestDTO.getCity(),guestDTO.getId_number(),guestDTO.getPhone_number()};
                
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(GuestDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }//GEN-LAST:event_btnreloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton edit_Btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcity;
    private javax.swing.JLabel labelcountry;
    private javax.swing.JLabel labelguestid;
    private javax.swing.JLabel labelguestid1;
    private javax.swing.JLabel labelidnumber;
    private javax.swing.JLabel labelmodifyguestdetail;
    private javax.swing.JLabel labelname;
    private javax.swing.JLabel labelphone;
    private javax.swing.JTable table;
    private javax.swing.JTextField textcity;
    private javax.swing.JTextField textcountry;
    private javax.swing.JTextField textguestid;
    private javax.swing.JTextField textidnumber;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textphone;
    // End of variables declaration//GEN-END:variables

    private void close() {
          textguestid.setText(null);
           textname.setText(null);
             textcountry.setText(null);
            textcity.setText(null);
            textphone.setText(null);
          textidnumber.setText(null);
        
        
    }
}
