/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

/**
 *
 * @author user
 */
public class ModifyReservation extends javax.swing.JPanel {

    /**
     * Creates new form ModifyReservation
     */
    public ModifyReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hedingpanal = new javax.swing.JPanel();
        labelmodifyroomreservation = new javax.swing.JLabel();
        labelmodifyguestdetail = new javax.swing.JLabel();

        labelmodifyroomreservation.setBackground(new java.awt.Color(0, 0, 153));
        labelmodifyroomreservation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelmodifyroomreservation.setForeground(new java.awt.Color(0, 102, 102));
        labelmodifyroomreservation.setText("Modify Room Reservation ");
        labelmodifyroomreservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelmodifyroomreservationMouseClicked(evt);
            }
        });

        labelmodifyguestdetail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelmodifyguestdetail.setForeground(new java.awt.Color(0, 102, 102));
        labelmodifyguestdetail.setText("Modify Guest Detail");
        labelmodifyguestdetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelmodifyguestdetailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hedingpanalLayout = new javax.swing.GroupLayout(hedingpanal);
        hedingpanal.setLayout(hedingpanalLayout);
        hedingpanalLayout.setHorizontalGroup(
            hedingpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hedingpanalLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(labelmodifyroomreservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addComponent(labelmodifyguestdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        hedingpanalLayout.setVerticalGroup(
            hedingpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelmodifyroomreservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelmodifyguestdetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(hedingpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hedingpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 891, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelmodifyguestdetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmodifyguestdetailMouseClicked
    ModifyGuestDetail m1=new ModifyGuestDetail();
    m1.setSize(jPanel1.getSize());
    jPanel1.add(m1);
    jPanel1.repaint();
    jPanel1.revalidate();
    }//GEN-LAST:event_labelmodifyguestdetailMouseClicked

    private void labelmodifyroomreservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmodifyroomreservationMouseClicked
      ModifyRoomReservation m1=new ModifyRoomReservation();
         m1.setSize(jPanel1.getSize());
         jPanel1.removeAll();
        jPanel1.add(m1);
        jPanel1.repaint();
        jPanel1.revalidate();

    }//GEN-LAST:event_labelmodifyroomreservationMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hedingpanal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelmodifyguestdetail;
    private javax.swing.JLabel labelmodifyroomreservation;
    // End of variables declaration//GEN-END:variables
}
