/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse43.hotelreservationsystem.Controller.QueryController;
import lk.ijse.gdse43.hotelreservationsystem.Controller.RoomController;
import lk.ijse.gdse43.hotelreservationsystem.Controller.RoomMidifyController;
import lk.ijse.gdse43.hotelreservationsystem.Controller.RoomTypeController;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.CustomeDTO;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.RoomDTO;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.RoomTypeDTO;
import static org.apache.commons.javaflow.Continuation.cancel;

/**
 *
 * @author user
 */
public class ModifyRooms extends javax.swing.JPanel {

    /**
     * Creates new form ModifyRooms
     */
    public ModifyRooms() {
        initComponents();
        loadroomId();
        clearAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        combo_roomId = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roomTypeId_Text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_View = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        Description = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rommTypeText = new javax.swing.JTextField();
        Price_Text = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        btn_view2 = new javax.swing.JButton();
        description_Text = new javax.swing.JTextField();
        btn_Edit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        RoomName_Text = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Modify Room ");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room Id", "Room Type Id", "Room_Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(table);

        combo_roomId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_roomIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Room Type Id");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Price");

        roomTypeId_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeId_TextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Room Id");

        btn_View.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_View.setForeground(new java.awt.Color(102, 102, 255));
        btn_View.setText("View");
        btn_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewActionPerformed(evt);
            }
        });

        btn_Clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(153, 102, 255));
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        Description.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Description.setForeground(new java.awt.Color(102, 102, 255));
        Description.setText("Description");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Room Type");

        rommTypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rommTypeTextActionPerformed(evt);
            }
        });

        Price_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price_TextActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RoomType Id", "Room Type", "Description"
            }
        ));
        jScrollPane2.setViewportView(table2);

        btn_view2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_view2.setForeground(new java.awt.Color(51, 51, 255));
        btn_view2.setText("View");
        btn_view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view2ActionPerformed(evt);
            }
        });

        description_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                description_TextActionPerformed(evt);
            }
        });

        btn_Edit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(153, 102, 255));
        btn_Edit.setText("Edit");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Room Name");

        RoomName_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomName_TextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Edit)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RoomName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rommTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(62, 62, 62)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combo_roomId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roomTypeId_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Price_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(description_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(515, 515, 515)
                                .addComponent(btn_View))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_Clear)
                                        .addGap(382, 382, 382)
                                        .addComponent(btn_view2))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 729, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(combo_roomId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(roomTypeId_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rommTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_View)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(RoomName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Description)
                            .addComponent(description_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Price_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(880, 880, 880))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Clear)
                            .addComponent(btn_Edit)
                            .addComponent(btn_view2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_roomIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_roomIdActionPerformed
        try {
            String id=combo_roomId.getSelectedItem().toString();
            CustomeDTO room=QueryController.getAllroomDetail(id);
            roomTypeId_Text.setText(room.getRoomType_Id());
            rommTypeText.setText(room.getRoomType());
            description_Text.setText(room.getDescription());
            RoomName_Text.setText(room.getRoom_Name());
         
           
            Price_Text.setText(Double.toString(room.getPrice()));
            
        } catch (Exception ex) {
            Logger.getLogger(ModifyRooms.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_combo_roomIdActionPerformed

    private void roomTypeId_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeId_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypeId_TextActionPerformed

    private void rommTypeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rommTypeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rommTypeTextActionPerformed

    private void Price_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price_TextActionPerformed

    private void btn_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewActionPerformed
            try {
            ArrayList<RoomDTO> list= RoomController.getAllRooms();
            DefaultTableModel dtm=(DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
           
            for (RoomDTO room : list) {
                Object[] rowData={room.getRoom_id(),room.getRoomType_Id(),room.getRoom_name(),room.getPrice()};
                
                dtm.addRow(rowData);
            }
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(RoomReseve.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ViewActionPerformed

    private void btn_view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view2ActionPerformed
        try {
            ArrayList<RoomTypeDTO>roomType=RoomTypeController.getAllRoomType();
            DefaultTableModel dtm=(DefaultTableModel) table2.getModel();
            dtm.setRowCount(0);
            
            for (RoomTypeDTO room : roomType) {
                Object[] rowData={room.getRoomType_Id(),room.getRoomType(),room.getDescription()};
                dtm.addRow(rowData);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyRooms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_view2ActionPerformed

    private void description_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_description_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_description_TextActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        try {
            RoomDTO room=new RoomDTO(Double.parseDouble(Price_Text.getText()),combo_roomId.getSelectedItem()+"",RoomName_Text.getText());
            RoomTypeDTO roomType=new RoomTypeDTO(roomTypeId_Text.getText(),rommTypeText.getText(),description_Text.getText());
            
            boolean result=RoomMidifyController.Update(room,roomType);
            System.out.println(result);
            if(result){
                JOptionPane.showMessageDialog(this,"Update");
                clearAll();
            }else{
               
                JOptionPane.showMessageDialog(this," not Update");
                clearAll();
            }
        } catch (IOException ex) {
            Logger.getLogger(ModifyRooms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_EditActionPerformed

    private void RoomName_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomName_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomName_TextActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        clearAll();
    }//GEN-LAST:event_btn_ClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JTextField Price_Text;
    private javax.swing.JTextField RoomName_Text;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_View;
    private javax.swing.JButton btn_view2;
    private javax.swing.JComboBox<String> combo_roomId;
    private javax.swing.JTextField description_Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField rommTypeText;
    private javax.swing.JTextField roomTypeId_Text;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables

    private void loadroomId() {
        
        try {
            ArrayList<String>room=RoomController.getRoomIds();
            
            for (String id : room) {
                combo_roomId.addItem(id);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ModifyRooms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAll() {
       roomTypeId_Text.setText(null);
       rommTypeText.setText(null);
       RoomName_Text.setText(null);
       description_Text.setText(null);
       Price_Text.setText(null);
    }
}
