/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

import java.awt.Color;
import java.awt.Dialog;
import java.io.IOException;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import lk.ijse.gdse43.hotelreservationsystem.Controller.PaymentController;
import lk.ijse.gdse43.hotelreservationsystem.Controller.RoomController;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.PaymentDTO;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.RoomDTO;
import lk.ijse.gdse43.hotelreservationsystem.dao.Db.DBConnection;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;

/**
 *
 * @author user
 */
@Report("lk.ijse.gdse43.hotelreservationsystem.jasper.report")
public class Payment extends javax.swing.JPanel {
    String checkIN;
    String checkOut;
    long fullCost;
   

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
       
                
        
        
    }

    /*Payment(String reservationId, String guest, String roomId, String date) {
        initComponents();
        reservationIDText.setText(reservationId);
        textguest1.setText(guest);
        textroomid.setText(roomId);
        textdate.setText(date);
                
    }*/

    Payment(String reservationId, String guest, String roomId, String date, String checkIn, String checkOut) {
        initComponents();
        reservationIDText.setText(reservationId);
        textguest1.setText(guest);
        textroomid.setText(roomId);
        textdate.setText(date);
        this.checkIN=checkIn;
        this.checkOut=checkOut;
        dateCount();
         loardtime();
        
    }
     private void dateCount() {

        SimpleDateFormat s1 = new SimpleDateFormat("yyyy-MM-dd");
        String in1 = checkIN;
        String in2 = checkOut;
        try {
            Date d1 = s1.parse(in1);
            Date d2 = s1.parse(in2);

            long diff = d2.getTime() - d1.getTime();
            long x = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
            System.out.println("Day : " + x);
            String roomId = textroomid.getText();
            
            try {
               RoomDTO  dto = RoomController.search(roomId);
               double roomPrice=dto.getPrice();
               System.out.println("price : " + roomPrice);
                fullCost=(long) (x*roomPrice);
               textamount.setText(""+fullCost);
            } catch (Exception ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelpaymentdetail = new javax.swing.JLabel();
        labelguestid = new javax.swing.JLabel();
        labelpaymentid = new javax.swing.JLabel();
        labeladvance = new javax.swing.JLabel();
        labeldate = new javax.swing.JLabel();
        labeltime = new javax.swing.JLabel();
        labelamount = new javax.swing.JLabel();
        textroomid = new javax.swing.JTextField();
        textdate = new javax.swing.JTextField();
        textadvance = new javax.swing.JTextField();
        textamount = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnprintbill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelreservationid1 = new javax.swing.JLabel();
        labelreservationid2 = new javax.swing.JLabel();
        reservationIDText = new javax.swing.JTextField();
        textguest1 = new javax.swing.JTextField();
        btnreload = new javax.swing.JButton();
        textarrears = new javax.swing.JTextField();
        labelarrears = new javax.swing.JLabel();
        textpaymentid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_time = new javax.swing.JTextField();

        labelpaymentdetail.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelpaymentdetail.setForeground(new java.awt.Color(255, 102, 102));
        labelpaymentdetail.setText("  Payment Detail");

        labelguestid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelguestid.setForeground(new java.awt.Color(102, 102, 255));
        labelguestid.setText("Guest Id");

        labelpaymentid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelpaymentid.setForeground(new java.awt.Color(102, 102, 255));
        labelpaymentid.setText("Payment Id");

        labeladvance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeladvance.setForeground(new java.awt.Color(102, 102, 255));
        labeladvance.setText("Advance");

        labeldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeldate.setForeground(new java.awt.Color(102, 102, 255));
        labeldate.setText("Date");

        labeltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeltime.setForeground(new java.awt.Color(102, 102, 255));
        labeltime.setText("Time");

        labelamount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelamount.setForeground(new java.awt.Color(102, 102, 255));
        labelamount.setText("Full Amount");

        textroomid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textroomidActionPerformed(evt);
            }
        });

        textdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdateActionPerformed(evt);
            }
        });

        textadvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textadvanceActionPerformed(evt);
            }
        });

        textamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textamountActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsave.setForeground(new java.awt.Color(102, 102, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnprintbill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnprintbill.setForeground(new java.awt.Color(102, 102, 255));
        btnprintbill.setText("Print Bill");
        btnprintbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprintbillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnprintbillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnprintbillMouseExited(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Payment Id", "Reservation Id", "Date", "Time", "Amount", "Advance"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        labelreservationid1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelreservationid1.setForeground(new java.awt.Color(102, 102, 255));
        labelreservationid1.setText("Reservation Id");

        labelreservationid2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelreservationid2.setForeground(new java.awt.Color(102, 102, 255));
        labelreservationid2.setText("Room Id");

        reservationIDText.setBorder(null);
        reservationIDText.setOpaque(false);

        textguest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textguest1ActionPerformed(evt);
            }
        });

        btnreload.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreload.setForeground(new java.awt.Color(102, 102, 255));
        btnreload.setText("Reload");
        btnreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreloadActionPerformed(evt);
            }
        });

        labelarrears.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelarrears.setForeground(new java.awt.Color(102, 102, 255));
        labelarrears.setText("Arrears");

        textpaymentid.setBorder(null);
        textpaymentid.setOpaque(false);

        jSeparator2.setForeground(new java.awt.Color(255, 0, 51));

        txt_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelreservationid2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelguestid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelreservationid1)))
                                        .addGap(80, 80, 80)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reservationIDText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textguest1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textpaymentid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnreload)
                                .addGap(266, 266, 266))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labeladvance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(textadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(labelamount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(77, 77, 77)
                                                    .addComponent(textamount, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(37, 37, 37)
                                        .addComponent(labelarrears, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(textarrears, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labeltime, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textdate, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsave)
                        .addGap(40, 40, 40)
                        .addComponent(btnprintbill)
                        .addGap(956, 956, 956))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(labelpaymentdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelpaymentdetail)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textamount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelpaymentid)
                        .addComponent(labelamount)
                        .addComponent(textpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelreservationid1)
                        .addComponent(reservationIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labeladvance)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelarrears)
                            .addComponent(textadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textarrears, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnreload)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave)
                            .addComponent(btnprintbill)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelguestid)
                            .addComponent(textguest1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelreservationid2)
                            .addComponent(textroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeldate)
                            .addComponent(textdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeltime)
                            .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(237, 237, 237))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdateActionPerformed

    private void btnreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreloadActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            PaymentDTO payment=new PaymentDTO(textpaymentid.getText(),reservationIDText.getText(),textdate.getText(),txt_time.getText(),Double.parseDouble(textamount.getText()),Double.parseDouble(textadvance.getText()));
            boolean reseult=PaymentController.addPaymetDetail(payment);
            System.out.println("binura");
            if(reseult){
                JOptionPane.showMessageDialog(this, "Added");
            }else{
                
                JOptionPane.showMessageDialog(this, " Not Added");
            }
        } catch (Exception ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void textadvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textadvanceActionPerformed
      double advanceCost=Double.parseDouble(textadvance.getText());
      double arreas=fullCost-advanceCost;
      textarrears.setText(""+arreas);
    }//GEN-LAST:event_textadvanceActionPerformed

    private void btnprintbillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintbillMouseEntered
       btnprintbill.setForeground(Color.black); 
    }//GEN-LAST:event_btnprintbillMouseEntered

    private void btnprintbillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintbillMouseExited
        btnprintbill.setForeground(Color.BLUE); 
    }//GEN-LAST:event_btnprintbillMouseExited

    private void textguest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textguest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textguest1ActionPerformed

    private void textamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textamountActionPerformed

    private void textroomidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textroomidActionPerformed
        System.out.println("");        // TODO add your handling code here:
    }//GEN-LAST:event_textroomidActionPerformed

    private void txt_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeActionPerformed

    private void btnprintbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintbillMouseClicked
        try {
            JasperUtil.init(Payment.class);
            
            JasperReportsContext ctx = JasperUtil.getReportContext();

            JasperReport compiledReport = JasperUtil.getCompiledReport("payment.jasper");
            JasperFillManager fillManeger = JasperFillManager.getInstance(ctx);

            HashMap<String, Object> reportParams = new HashMap<>();

            reportParams.put("paymentid",textpaymentid.getText());
             reportParams.put("resavationid",reservationIDText.getText());
             reportParams.put("advance",textadvance.getText());
              reportParams.put("amount",textamount.getText());
              reportParams.put("arrears",textarrears.getText());
            

            Connection conn =DBConnection.getInstance().getConnection();

            JasperPrint fillreport = fillManeger.fill(compiledReport, reportParams,new JREmptyDataSource());

            IJSEJasperViewer frmJasperViewr = new IJSEJasperViewer(fillreport);
            frmJasperViewr.setTitle("Fast Moving Item Report");
            frmJasperViewr.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            frmJasperViewr.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnprintbillMouseClicked
   public void loardtime(){
        
            Calendar c=Calendar.getInstance();
            SimpleDateFormat df=new SimpleDateFormat("hh.mm");
            String time=df.format(c.getTime());
            txt_time.setText(time);
            
        
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprintbill;
    private javax.swing.JButton btnreload;
    private javax.swing.JButton btnsave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labeladvance;
    private javax.swing.JLabel labelamount;
    private javax.swing.JLabel labelarrears;
    private javax.swing.JLabel labeldate;
    private javax.swing.JLabel labelguestid;
    private javax.swing.JLabel labelpaymentdetail;
    private javax.swing.JLabel labelpaymentid;
    private javax.swing.JLabel labelreservationid1;
    private javax.swing.JLabel labelreservationid2;
    private javax.swing.JLabel labeltime;
    private javax.swing.JTextField reservationIDText;
    private javax.swing.JTextField textadvance;
    private javax.swing.JTextField textamount;
    private javax.swing.JTextField textarrears;
    private javax.swing.JTextField textdate;
    private javax.swing.JTextField textguest1;
    private javax.swing.JTextField textpaymentid;
    private javax.swing.JTextField textroomid;
    private javax.swing.JTextField txt_time;
    // End of variables declaration//GEN-END:variables

 
