/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

/**
 *
 * @author user
 */
public class Reservation extends javax.swing.JPanel {

    /**
     * Creates new form Checking_Checkout
     */
    public Reservation() {
        initComponents();
    }

    Reservation(String text, String text0, String text1, String text2, String text3, String text4) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hedingpanal = new javax.swing.JPanel();
        paymentdetaillabel = new javax.swing.JLabel();
        settlethedatelabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1631, 926));

        paymentdetaillabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        paymentdetaillabel.setForeground(new java.awt.Color(0, 102, 102));
        paymentdetaillabel.setText("Payment Detail");
        paymentdetaillabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentdetaillabelMouseClicked(evt);
            }
        });

        settlethedatelabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        settlethedatelabel.setForeground(new java.awt.Color(0, 102, 102));
        settlethedatelabel.setText("  Settle The Date");
        settlethedatelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlethedatelabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hedingpanalLayout = new javax.swing.GroupLayout(hedingpanal);
        hedingpanal.setLayout(hedingpanalLayout);
        hedingpanalLayout.setHorizontalGroup(
            hedingpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hedingpanalLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(settlethedatelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(paymentdetaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        hedingpanalLayout.setVerticalGroup(
            hedingpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hedingpanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hedingpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentdetaillabel)
                    .addComponent(settlethedatelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1630, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hedingpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hedingpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void settlethedatelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settlethedatelabelMouseClicked
        SettleTheDate d1=new SettleTheDate();
        d1.setSize(jPanel2.getSize());
        jPanel2.removeAll();
        jPanel2.add(d1);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_settlethedatelabelMouseClicked

    private void paymentdetaillabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentdetaillabelMouseClicked
        Payment p1=new Payment();
        p1.setSize(jPanel2.getSize());
        
        jPanel2.removeAll();
        jPanel2.add(p1);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_paymentdetaillabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hedingpanal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel paymentdetaillabel;
    private javax.swing.JLabel settlethedatelabel;
    // End of variables declaration//GEN-END:variables
}
