/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse43.hotelreservationsystem.Controller.GuestController;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.GuestDTO;

/**
 *
 * @author user
 */
public class ViewGuestDetail extends javax.swing.JPanel {

    /** Creates new form ViewGuestDetail */
    public ViewGuestDetail() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelviewguestdetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGuest = new javax.swing.JTable();
        btnreload = new javax.swing.JButton();

        labelviewguestdetail.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelviewguestdetail.setForeground(new java.awt.Color(255, 102, 102));
        labelviewguestdetail.setText("View Guest Detail");

        tableGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Guest Id", "Name", "Country", "City", "Id_Number", "Phone_Number"
            }
        ));
        jScrollPane1.setViewportView(tableGuest);

        btnreload.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreload.setForeground(new java.awt.Color(102, 102, 255));
        btnreload.setText("Reload");
        btnreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnreload)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(labelviewguestdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(672, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelviewguestdetail)
                .addGap(109, 109, 109)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btnreload)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreloadActionPerformed
        try {
            ArrayList<GuestDTO> guest= GuestController.getAllGuest();
            DefaultTableModel dtm=(DefaultTableModel) tableGuest.getModel();
            dtm.setRowCount(0);
            
            for (GuestDTO guestDTO : guest) {
                Object[] rowData={guestDTO.getGuest_id(),guestDTO.getName(),guestDTO.getCountry(),guestDTO.getCity(),guestDTO.getId_number(),guestDTO.getPhone_number()};
                
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(GuestDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnreloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelviewguestdetail;
    private javax.swing.JTable tableGuest;
    // End of variables declaration//GEN-END:variables

}
