/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.ParseConversionEvent;
import lk.ijse.gdse43.hotelreservationsystem.Controller.PaymentController;
import lk.ijse.gdse43.hotelreservationsystem.Controller.QueryController;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.CustomeDTO;
import lk.ijse.gdse43.hotelreservationsystem.core.dto.PaymentDTO;

/**
 *
 * @author user
 */
public class ViewFullPaymentandPrintBill extends javax.swing.JPanel {

    /**
     * Creates new form ViewFullPaymentandPrintBill
     */
    public ViewFullPaymentandPrintBill() {
        initComponents();
        loadPaymentId();
        loadTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelpaymentdetail = new javax.swing.JLabel();
        labelreservationid = new javax.swing.JLabel();
        labelroomid = new javax.swing.JLabel();
        labeldate = new javax.swing.JLabel();
        labeltime = new javax.swing.JLabel();
        labelfullamount = new javax.swing.JLabel();
        combopaymentid = new javax.swing.JComboBox<>();
        btnprintbill = new javax.swing.JButton();
        Text_time = new javax.swing.JTextField();
        textreservationid = new javax.swing.JTextField();
        textdate = new javax.swing.JTextField();
        textfullamount = new javax.swing.JTextField();
        labelpaymentid1 = new javax.swing.JLabel();
        textroomid = new javax.swing.JTextField();
        labelguest1 = new javax.swing.JLabel();
        textguest1 = new javax.swing.JTextField();
        labelsettlefullpayment = new javax.swing.JLabel();
        Text_Arrears = new javax.swing.JTextField();
        labeladvance = new javax.swing.JLabel();
        textadvance = new javax.swing.JTextField();

        labelpaymentdetail.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelpaymentdetail.setForeground(new java.awt.Color(255, 102, 102));
        labelpaymentdetail.setText("  Full Payment Detail & Print Bill");

        labelreservationid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelreservationid.setForeground(new java.awt.Color(102, 102, 255));
        labelreservationid.setText("Reservation Id");

        labelroomid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelroomid.setForeground(new java.awt.Color(102, 102, 255));
        labelroomid.setText("Room Id");

        labeldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeldate.setForeground(new java.awt.Color(102, 102, 255));
        labeldate.setText("Date");

        labeltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeltime.setForeground(new java.awt.Color(102, 102, 255));
        labeltime.setText("Time");

        labelfullamount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelfullamount.setForeground(new java.awt.Color(102, 102, 255));
        labelfullamount.setText("Full Amount");

        combopaymentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopaymentidActionPerformed(evt);
            }
        });

        btnprintbill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnprintbill.setForeground(new java.awt.Color(102, 102, 255));
        btnprintbill.setText("Print Bill");

        textdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdateActionPerformed(evt);
            }
        });

        labelpaymentid1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelpaymentid1.setForeground(new java.awt.Color(102, 102, 255));
        labelpaymentid1.setText("Payment Id");

        labelguest1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelguest1.setForeground(new java.awt.Color(102, 102, 255));
        labelguest1.setText("Guest Id");

        labelsettlefullpayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelsettlefullpayment.setForeground(new java.awt.Color(102, 102, 255));
        labelsettlefullpayment.setText("Arrears");

        Text_Arrears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_ArrearsActionPerformed(evt);
            }
        });

        labeladvance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeladvance.setForeground(new java.awt.Color(102, 102, 255));
        labeladvance.setText("Advance");

        textadvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textadvanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(labelpaymentdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 570, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labeltime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(195, 195, 195))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelguest1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelreservationid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelpaymentid1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Text_time)
                                .addComponent(combopaymentid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textreservationid)
                                .addComponent(textroomid)
                                .addComponent(textguest1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textdate, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelfullamount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelsettlefullpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfullamount, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Arrears, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(177, 177, 177))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(btnprintbill))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labeladvance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158)
                                .addComponent(textadvance)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelpaymentdetail)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combopaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelpaymentid1))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textreservationid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelreservationid)
                            .addComponent(labeladvance)
                            .addComponent(textadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelfullamount)
                        .addComponent(textfullamount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelguest1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelsettlefullpayment)
                            .addComponent(Text_Arrears, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textguest1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelroomid)
                    .addComponent(textroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldate)
                    .addComponent(textdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltime)
                    .addComponent(Text_time, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(btnprintbill)
                .addGap(184, 184, 184))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdateActionPerformed

    private void Text_ArrearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_ArrearsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_ArrearsActionPerformed

    private void combopaymentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopaymentidActionPerformed
        try {
            String id=combopaymentid.getSelectedItem().toString();
            CustomeDTO cust=QueryController.getAllDetails(id);
            textreservationid.setText(cust.getR_id());
            textguest1.setText(cust.getGuest_id());
            textroomid.setText(cust.getRommId());
            textdate.setText(cust.getDate());
            textfullamount.setText(Double.toString(cust.getAmount()));
            textadvance.setText(Double.toString(cust.getAdvance()));
        } catch (Exception ex) {
            Logger.getLogger(ViewFullPaymentandPrintBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combopaymentidActionPerformed

    private void textadvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textadvanceActionPerformed
        double amount=Double.parseDouble(textfullamount.getText());
        double addvance=Double.parseDouble(textadvance.getText());
      double arreas=amount-addvance;
      Text_Arrears.setText(""+arreas);
    }//GEN-LAST:event_textadvanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_Arrears;
    private javax.swing.JTextField Text_time;
    private javax.swing.JButton btnprintbill;
    private javax.swing.JComboBox<String> combopaymentid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeladvance;
    private javax.swing.JLabel labeldate;
    private javax.swing.JLabel labelfullamount;
    private javax.swing.JLabel labelguest1;
    private javax.swing.JLabel labelpaymentdetail;
    private javax.swing.JLabel labelpaymentid1;
    private javax.swing.JLabel labelreservationid;
    private javax.swing.JLabel labelroomid;
    private javax.swing.JLabel labelsettlefullpayment;
    private javax.swing.JLabel labeltime;
    private javax.swing.JTextField textadvance;
    private javax.swing.JTextField textdate;
    private javax.swing.JTextField textfullamount;
    private javax.swing.JTextField textguest1;
    private javax.swing.JTextField textreservationid;
    private javax.swing.JTextField textroomid;
    // End of variables declaration//GEN-END:variables

    private void loadPaymentId() {
        
       
        try {
            ArrayList<PaymentDTO>payment=PaymentController.getPaymentIds();
            for (PaymentDTO pay : payment) {
              combopaymentid.addItem(pay.getPayment_Id());
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewFullPaymentandPrintBill.class.getName()).log(Level.SEVERE, null, ex);
        }
            }

    private void loadTime() {
         Calendar c=Calendar.getInstance();
            SimpleDateFormat df=new SimpleDateFormat("hh.mm");
            String time=df.format(c.getTime());
            Text_time.setText(time);
    }
       
    
}
