/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse43.hotelroomreservationsystem.view.panal;

/**
 *
 * @author user
 */
public class ViewReseveDetail extends javax.swing.JPanel {

    /**
     * Creates new form ViewReseveDetail
     */
    public ViewReseveDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hedingpanal = new javax.swing.JPanel();
        labelviewguestdetail = new javax.swing.JLabel();
        labelviewroomreservation = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        labelviewguestdetail.setBackground(new java.awt.Color(0, 0, 153));
        labelviewguestdetail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelviewguestdetail.setForeground(new java.awt.Color(0, 102, 102));
        labelviewguestdetail.setText("View Guest Detail");
        labelviewguestdetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelviewguestdetailMouseClicked(evt);
            }
        });

        labelviewroomreservation.setBackground(new java.awt.Color(0, 0, 153));
        labelviewroomreservation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelviewroomreservation.setForeground(new java.awt.Color(0, 102, 102));
        labelviewroomreservation.setText("View Room Reservation");
        labelviewroomreservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelviewroomreservationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hedingpanalLayout = new javax.swing.GroupLayout(hedingpanal);
        hedingpanal.setLayout(hedingpanalLayout);
        hedingpanalLayout.setHorizontalGroup(
            hedingpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hedingpanalLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(labelviewroomreservation, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                .addComponent(labelviewguestdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        hedingpanalLayout.setVerticalGroup(
            hedingpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hedingpanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hedingpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelviewguestdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelviewroomreservation, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1630, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hedingpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hedingpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelviewguestdetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelviewguestdetailMouseClicked
        ViewGuestDetail v1=new ViewGuestDetail();
        v1.setSize(jPanel2.getSize());
        jPanel2.removeAll();
        jPanel2.add(v1);
        jPanel2.repaint();
        jPanel2.revalidate();

    }//GEN-LAST:event_labelviewguestdetailMouseClicked

    private void labelviewroomreservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelviewroomreservationMouseClicked
        ViewRoomReservationDetail v1=new ViewRoomReservationDetail();
        v1.setSize(jPanel2.getSize());
         jPanel2.removeAll();
        jPanel2.add(v1);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_labelviewroomreservationMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hedingpanal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelviewguestdetail;
    private javax.swing.JLabel labelviewroomreservation;
    // End of variables declaration//GEN-END:variables
}
